services:
  nginx:
    image: nginx:latest
    container_name: nginx-services
    restart: always
    networks:
      - dbnet
    expose:
      - 8088
    ports:
      - "80:8088"
    volumes:
      - ./easyenglish/media:/home/easyenglish/media
      - ./easyenglish/static:/home/easyenglish/static
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - easyenglish
  easyenglish:
    build: ./easyenglish
    image: easyenglish
    container_name: easyenglish
    restart: always
    env_file:
      - .env
    links:
      - "postgres:dbps"
    networks:
      - dbnet
    volumes:
      - ./easyenglish:/home/easyenglish
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - DJANGO_DEBUG=true
      - "5678:5678"
    environment:
      - DJANGO_DEBUG=true
    depends_on:
      - postgres
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "82:80"
    links:
      - "postgres:db"
    networks:
      - dbnet
    depends_on:
      - postgres      
  postgres:
    image: postgres:16.9
    container_name: psgr
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - dbnet

volumes:
  postgres-data:

networks:
  dbnet:
    driver: bridge