# Generated by Django 5.1.3 on 2024-12-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0003_remove_relatedword_relate_english_word'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedEnglishWord',
        ),
    ]
