# Generated by Django 5.2 on 2025-05-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0005_relatedenglishword_relatedword_relate_english_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='english',
            name='example',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
