# Generated by Django 4.2.5 on 2023-10-27 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('ngsl_number', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Russian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VerbCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.english')),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.card')),
                ('russian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.russian')),
            ],
        ),
        migrations.CreateModel(
            name='NounCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.english')),
            ],
        ),
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.card')),
                ('russian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.russian')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='english',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
        ),
        migrations.CreateModel(
            name='AdjectiveCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.english')),
            ],
        ),
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.card')),
                ('russian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.russian')),
            ],
        ),
    ]
