# Generated by Django 5.1.3 on 2024-12-13 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conjunction',
            name='english',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
        ),
        migrations.AddField(
            model_name='comment',
            name='english',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
        ),
        migrations.AddField(
            model_name='adverb',
            name='english',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
        ),
        migrations.AddField(
            model_name='adjective',
            name='english',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
        ),
        migrations.AddField(
            model_name='exampleword',
            name='english',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
        ),
        migrations.AddField(
            model_name='exampleword',
            name='example',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.example'),
        ),
        migrations.AddField(
            model_name='fpos',
            name='english',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
        ),
        migrations.AddField(
            model_name='book',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ee.level'),
        ),
        migrations.AddField(
            model_name='noun',
            name='english',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
        ),
        migrations.AddField(
            model_name='preposition',
            name='english',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
        ),
        migrations.AddField(
            model_name='pronoun',
            name='english',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
        ),
        migrations.AddField(
            model_name='relatedword',
            name='english',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
        ),
        migrations.AddField(
            model_name='relatedword',
            name='relate_english_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.relatedenglishword'),
        ),
        migrations.AddField(
            model_name='pronoun',
            name='russian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.russian'),
        ),
        migrations.AddField(
            model_name='preposition',
            name='russian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.russian'),
        ),
        migrations.AddField(
            model_name='noun',
            name='russian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.russian'),
        ),
        migrations.AddField(
            model_name='fpos',
            name='russian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.russian'),
        ),
        migrations.AddField(
            model_name='conjunction',
            name='russian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.russian'),
        ),
        migrations.AddField(
            model_name='adverb',
            name='russian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.russian'),
        ),
        migrations.AddField(
            model_name='adjective',
            name='russian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.russian'),
        ),
        migrations.AddField(
            model_name='verb',
            name='english',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
        ),
        migrations.AddField(
            model_name='verb',
            name='russian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.russian'),
        ),
        migrations.AddField(
            model_name='wordbook',
            name='english',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
        ),
        migrations.AddField(
            model_name='wordbook',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
