# Generated by Django 4.2.5 on 2023-10-31 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0002_pronouncard_pronoun'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepositionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.english')),
            ],
        ),
        migrations.CreateModel(
            name='Preposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.card')),
                ('russian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.russian')),
            ],
        ),
    ]
