# Generated by Django 4.2.6 on 2023-11-02 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0004_conjunctioncard_conjunction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedEnglishWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.card')),
                ('relate_english_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.relatedenglishword')),
            ],
        ),
        migrations.CreateModel(
            name='Fpos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.card')),
                ('russian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.russian')),
            ],
        ),
    ]
