# Generated by Django 4.2.6 on 2023-11-03 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0006_example_exampleword'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverbCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.english')),
            ],
        ),
        migrations.CreateModel(
            name='Adverb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.card')),
                ('russian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee.russian')),
            ],
        ),
    ]
