# Generated by Django 4.2.6 on 2023-11-23 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0008_wordbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordbook',
            name='card',
        ),
        migrations.AddField(
            model_name='wordbook',
            name='english',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
            preserve_default=False,
        ),
    ]
