# Generated by Django 4.2.6 on 2023-12-01 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0011_alter_comment_options_comment_active_comment_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='english',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='perent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ee.comment'),
        ),
    ]
