# Generated by Django 4.2.6 on 2023-12-01 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0012_alter_comment_english_alter_comment_perent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='perent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ee.comment'),
        ),
    ]
