# Generated by Django 4.2.6 on 2023-12-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0013_alter_comment_perent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
