# Generated by Django 4.2.6 on 2023-12-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0014_alter_comment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='perent',
            new_name='parent',
        ),
    ]
