# Generated by Django 4.2.6 on 2023-12-25 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0015_rename_perent_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('unique_words', models.SmallIntegerField()),
                ('total_words', models.SmallIntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='wordbook',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='Bookcontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_english', models.CharField(blank=True, default='', max_length=1000)),
                ('sentence_russian', models.CharField(blank=True, default='', max_length=1000)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ee.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ee.level'),
        ),
    ]
