# Generated by Django 4.2.6 on 2023-12-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0016_book_level_alter_wordbook_options_bookcontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcontent',
            name='page',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
