# Generated by Django 4.2.6 on 2024-01-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0017_bookcontent_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcontent',
            name='chapter',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='bookcontent',
            name='chapterName',
            field=models.BooleanField(null=True),
        ),
    ]
