# Generated by Django 4.2.6 on 2024-08-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0018_bookcontent_chapter_bookcontent_chaptername'),
    ]

    operations = [
        migrations.CreateModel(
            name='serv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(blank=True, default='', max_length=30)),
                ('parts_speech', models.CharField(blank=True, default='', max_length=30)),
                ('translate', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WordLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('Wordlist', models.CharField(blank=True, default='', max_length=30)),
                ('WL_SFI_Rank', models.SmallIntegerField()),
                ('RawFreq_Rank', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookcontent',
            options={'ordering': ('id',)},
        ),
    ]
