# Generated by Django 4.2.6 on 2024-08-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0019_serv_wordlists_alter_bookcontent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serv',
            name='english',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='serv',
            name='parts_speech',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='serv',
            name='translate',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
