# Generated by Django 4.2.6 on 2024-08-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0020_alter_serv_english_alter_serv_parts_speech_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serv',
            name='english',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='serv',
            name='parts_speech',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='serv',
            name='translate',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
