# Generated by Django 4.2.6 on 2024-08-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0021_alter_serv_english_alter_serv_parts_speech_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serv',
            name='transcription_eng',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='serv',
            name='transcription_use',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
