# Generated by Django 4.2.6 on 2024-09-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0023_serv_sound_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='english',
            name='sound_path',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='english',
            name='transcription',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
