# Generated by Django 4.2.6 on 2024-09-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0024_english_sound_path_english_transcription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='english',
            name='sound_path',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
