# Generated by Django 4.2.6 on 2024-09-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0025_alter_english_sound_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='english',
            name='sound_path',
            field=models.FileField(upload_to='media/'),
        ),
    ]
