# Generated by Django 4.2.6 on 2024-10-10 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0026_alter_english_sound_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adverbcard',
            name='english',
        ),
        migrations.RemoveField(
            model_name='conjunctioncard',
            name='english',
        ),
        migrations.RemoveField(
            model_name='nouncard',
            name='english',
        ),
        migrations.RemoveField(
            model_name='pronouncard',
            name='english',
        ),
        migrations.RemoveField(
            model_name='verbcard',
            name='english',
        ),
        migrations.AlterModelOptions(
            name='english',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='adjective',
            name='card',
        ),
        migrations.AddField(
            model_name='adjective',
            name='english',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdjectiveCard',
        ),
        migrations.DeleteModel(
            name='AdverbCard',
        ),
        migrations.DeleteModel(
            name='ConjunctionCard',
        ),
        migrations.DeleteModel(
            name='NounCard',
        ),
        migrations.DeleteModel(
            name='PronounCard',
        ),
        migrations.DeleteModel(
            name='VerbCard',
        ),
    ]
