# Generated by Django 4.2.6 on 2024-10-11 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0027_remove_adverbcard_english_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adverb',
            name='card',
        ),
        migrations.RemoveField(
            model_name='conjunction',
            name='card',
        ),
        migrations.RemoveField(
            model_name='exampleword',
            name='card',
        ),
        migrations.RemoveField(
            model_name='fpos',
            name='card',
        ),
        migrations.RemoveField(
            model_name='noun',
            name='card',
        ),
        migrations.RemoveField(
            model_name='preposition',
            name='card',
        ),
        migrations.RemoveField(
            model_name='pronoun',
            name='card',
        ),
        migrations.RemoveField(
            model_name='relatedword',
            name='card',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='card',
        ),
        migrations.AddField(
            model_name='adverb',
            name='english',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conjunction',
            name='english',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exampleword',
            name='english',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fpos',
            name='english',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noun',
            name='english',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preposition',
            name='english',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pronoun',
            name='english',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatedword',
            name='english',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verb',
            name='english',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ee.english'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PrepositionCard',
        ),
    ]
