# Generated by Django 5.1.3 on 2024-11-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0028_remove_adverb_card_remove_conjunction_card_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordbook',
            options={'ordering': ['english']},
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
